### PR TITLE
SLING-10043 - Naming OSGi configs with dashes breaks the OSGi installer

### PR DESCRIPTION
**Pull request by akankshajain18**

### CODE REVIEW

**Comment by rombert** [comment]
@cziegeler - code LGTM, but I have very little experience with the OSGi installer's inner workings.

**Review by cziegeler — APPROVED** [review]
Yes, lgtm - thanks

**Comment by rombert** [comment]
Thanks for the PR @akankshajain18 , I've tweaked it slightly and pushed to master.

**Comment by akankshajain18** [comment]
Thank you @rombert and @cziegeler

**Pull request closed without merging**
